import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';
import { GenerateReportPayload, ReportResponse } from '@/lib/types';
import { SYSTEM_PROMPT, buildUserPrompt } from '@/lib/prompts';
import { getSupabaseClient } from '@/lib/supabase';

export async function POST(request: NextRequest) {
  try {
    const body: GenerateReportPayload = await request.json();
    const { date, activities } = body;

    if (!date || !activities || activities.length === 0) {
      return NextResponse.json(
        { success: false, error: 'Date and at least one activity are required' } as ReportResponse,
        { status: 400 }
      );
    }

    for (const activity of activities) {
      if (!activity.time || !activity.description) {
        return NextResponse.json(
          { success: false, error: 'Each activity must have a time and description' } as ReportResponse,
          { status: 400 }
        );
      }
    }

    const apiKey = process.env.DEEPSEEK_API_KEY;
    const apiUrl = process.env.DEEPSEEK_API_URL || 'https://api.deepseek.com/v1';

    if (!apiKey) {
      return NextResponse.json(
        { success: false, error: 'DeepSeek API key not configured' } as ReportResponse,
        { status: 500 }
      );
    }

    const client = new OpenAI({ apiKey: apiKey, baseURL: apiUrl });
    const userPrompt = buildUserPrompt(date, activities);

    const completion = await client.chat.completions.create({
      model: 'deepseek-chat',
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.3,
      max_tokens: 2000,
    });

    const report = completion.choices[0]?.message?.content;

    if (!report) {
      return NextResponse.json(
        { success: false, error: 'No report generated by AI' } as ReportResponse,
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      report: report.trim(),
    } as ReportResponse);

  } catch (error) {
    console.error('Report generation error:', error);
    
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to generate report',
      } as ReportResponse,
      { status: 500 }
    );
  }
}
