import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';
import { GenerateReportPayload, ReportResponse } from '@/lib/types';
import { SYSTEM_PROMPT, buildUserPrompt } from '@/lib/prompts';
import { getSupabaseClient } from '@/lib/supabase';

/**
 * API Route: POST /api/generate-report
 * Generates a professional daily report using DeepSeek AI and saves it to database
 */
export async function POST(request: NextRequest) {
  try {
    // Parse request body
    const body: GenerateReportPayload = await request.json();
    const { date, activities } = body;

    // Validate input
    if (!date || !activities || activities.length === 0) {
      return NextResponse.json(
        {
          success: false,
          error: 'Date and at least one activity are required',
        } as ReportResponse,
        { status: 400 }
      );
    }

    // Validate each activity has time and description
    for (const activity of activities) {
      if (!activity.time || !activity.description) {
        return NextResponse.json(
          {
            success: false,
            error: 'Each activity must have a time and description',
          } as ReportResponse,
          { status: 400 }
        );
      }
    }

    // Initialize DeepSeek client (OpenAI-compatible)
    const apiKey = process.env.DEEPSEEK_API_KEY;
    const apiUrl = process.env.DEEPSEEK_API_URL || 'https://api.deepseek.com/v1';

    if (!apiKey) {
      return NextResponse.json(
        {
          success: false,
          error: 'DeepSeek API key not configured',
        } as ReportResponse,
        { status: 500 }
      );
    }

    const client = new OpenAI({
      apiKey: apiKey,
      baseURL: apiUrl,
    });

    // Build user prompt from activities
    const userPrompt = buildUserPrompt(date, activities);

    // Call DeepSeek API
    const completion = await client.chat.completions.create({
      model: 'deepseek-chat', // Use the appropriate model name
      messages: [
        {
          role: 'system',
          content: SYSTEM_PROMPT,
        },
        {
          role: 'user',
          content: userPrompt,
        },
      ],
      temperature: 0.3, // Low temperature for consistency
      max_tokens: 2000,
    });

    // Extract generated report
    const report = completion.choices[0]?.message?.content;

    if (!report) {
      return NextResponse.json(
        {
          success: false,
          error: 'No report generated by AI',
        } as ReportResponse,
        { status: 500 }
      );
    }

    // Return success response WITHOUT saving to database
    // User must click "Save to History" button to save
    return NextResponse.json({
      success: true,
      report: report.trim(),
    } as ReportResponse);

  } catch (error) {
    console.error('Report generation error:', error);
    
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to generate report',
      } as ReportResponse,
      { status: 500 }
    );
  }
}
